package prova2;

public enum TitulacaoAcademicaEnum {
	ENSINO_FUNDAMENTAL,
	ENSINO_MEDIO,
	TECNOLOGO,
	ENSINO_SUPERIOR_INCOMPLETO,
	ENSINO_SUPERIOR_COMPLETO_LICENCIATURA,
	ENSINO_SUPERIOR_COMPLETO_BACHARELADO,
	ESPECIALIZACAO,
	MESTRADO,
	DOUTORADO,
	POS_DOUTORADO
}